language: node_js
node_js:
- stable
services:
  – mongodb
deploy:
  provider: heroku
  api_key:
    secure: fOtUcAsNPe++SI+bnnT6cdw2BG9Y4GHym+RTepq3k0Ld+vJ5mV0vuvDxNRq19VaITmH61nrzOA54m3UirJCJxG2nPMS4ZVSaFd30AVItloCY3vyU3xqaIaVfia3VeljhERgWSPhck5zXJScu8HZL5Jl1GYJOx2SBmbVsaRHgCJN/4BDGVDltJwLPMFz173lLKGZLBr9vZmDNsmdE3ONcxwIqRrENawKcl6qn57h4keDuK4WdIo4a0kDbT1i3XlKeezTHdBNTYzxJRhD3K6iYqAAX++XPqIhPALVk+TRyUY+DS2WY+AZlhve+vr+h+JRbvJLJPWs6+LZbl3eNmoQ4kmWb8NCdtVF/MF/Qe/5QzM4NAGLQLgSOFqGmkuh8UX8zy9+Lr6/MJgXWVIaop8RZvC7QZW+5cwIDixhC3P2wiltU3WqpFEl1+HDnUh4J1Utzw93oMoI8vBQYSXVNlnrzfIZxu7Pc3W/mDJI8R6MHQHziSEyAQjn+wdA500d7yDNJjR4nsFZ83/RRdZTwOkcT0LpjeIq6TEikMsM9d9oxGx7qN9QwCbmlpvdWkZvfzTIkTjqFPwU2469Pi3feeQUp/FtmfJ2P51HMPYxPJOzG70Iz7V11rQ3lX8mxU5uilV9iVMf81b2ic7SKNL6DLXykDKTcKp7vzDmFctqXFd4Gt8Y=
  app: express-project-blog