language: node_js
node_js:
- stable
services:
  – mongodb
deploy:
  provider: heroku
  api_key:
    secure: Dy3aEWkHhTIOq+BjHpJhkgLNGtuvfPvY3HYFxiZygOzK2vjmzVtMi4u5y4ufBloMLlWHhNSBRKv/wTt/xdgaHd5kLEASKOPPyAYChmUTh0H/xtGGcJFN/M9xDGIRHJ9kyt99nkBNP8NUF3gzHxf4+3qdxdUQscyODKSAdYGdwVNaIPituVmh8hIkK5444b6hV+IGcCUOquQTZZENVkPEISxLILFunCIgVhfyNi6pqfe46R5fTZXv3TZ1kv1DhDSf8hZNxs5rzXpymA7TGKWIUEqOfU8iRdl6JV6R9o5t7eRKDrap0X4Srdwe/DIbXLcnZHRr9uLKnePVDahXCeEr97yGJbqJT3fG8E1Qe3BVkJCE7KmMjR8Sg7vmysb3VYrsr/a121HDSRrW5ozmCfnSkUMae9pDIUi7jNjXJDAGG/6noCum+D2xpKNQEMT4nWtBC7NENRxJvGdJeQC76tgHXRqqH6iIxWh05SJEx/q1+LGDa6yA8baSzLz479PMiqBod8Ap9LvB3Mj8nXiGtKneofKERIYWilCPLxcikPdyMeAq0S84tV3ZMCAE/9gyaibEFAVBtb2kHiifM+NgrrGVF4sw0YQNnqQGa1HXqf6FKuhJ3B4Oddtw5lPdJ3rFpYtpAA2ljbIyLM5J00YLwEbWMKHHih4joP07Vn29Saz3Fxw=